# Generated by Django 5.1 on 2024-11-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_delete_addcourse'),
        ('adminapp', '0005_contact'),
    ]

    operations = [
    ]
